title: Quantum-Inspired Unconventional Computing
description: Structure, state, and dynamics as computational resources
baseurl: "/qiuc"
url: "https://merementchouk.github.io"

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: null # Prevent kramdown from mangling raw LaTeX for KaTeX
exclude:
  - org/
  - README.md

